import Foundation
import SwiftUI

/// 语言设置：默认跟随系统，可手动覆盖（运行时即时切换，无需重启）
enum AppLanguage: String, CaseIterable, Identifiable {
    case system
    case english = "en"
    case simplifiedChinese = "zh-Hans"

    var id: String { rawValue }
}

@MainActor
final class Loc: ObservableObject {
    static let shared = Loc()
    private static let defaultsKey = "OpenToggle.language"

    @Published var language: AppLanguage {
        didSet {
            UserDefaults.standard.set(language.rawValue, forKey: Self.defaultsKey)
            // 非 SwiftUI 的菜单栏元素（NSStatusItem 菜单）需要主动重建
            SwitchManager.shared.languageDidChange()
        }
    }

    private init() {
        let raw = UserDefaults.standard.string(forKey: Self.defaultsKey)
        language = raw.flatMap(AppLanguage.init(rawValue:)) ?? .system
    }

    /// 当前生效的字符串表
    var s: S {
        switch language {
        case .english: return .en
        case .simplifiedChinese: return .zh
        case .system:
            let preferred = Locale.preferredLanguages.first ?? "en"
            return preferred.hasPrefix("zh") ? .zh : .en
        }
    }
}

// MARK: - 字符串表

/// 全部 UI 字符串。帮助文本支持 Markdown（**粗体**、`代码`）。
struct S {
    // 通用
    let cancel: String
    let langSystem: String

    // 菜单栏面板
    let panelEmpty: String
    let manageScripts: String
    let manageScriptsHelp: String
    let reloadHelp: String
    let quit: String
    let editScriptFile: String
    let revealInFinder: String
    let daemonRowHelp: String
    let toggleRowHelp: String
    let paramLiveNote: String
    let languageHelp: String

    // 状态栏（脚本声明的图标）
    let turnOffFormat: String // %@ = 开关名

    // 管理器 — 侧边栏
    let managerWindowTitle: String
    let newSwitch: String
    let openFolderHelp: String
    let deleteToTrash: String
    let selectPromptTitle: String
    let selectPromptDetail: String
    let showInMenuBar: String
    let hideFromMenuBar: String

    // 管理器 — 未保存
    let discardTitle: String
    let discardConfirm: String
    let keepEditing: String
    let discardMessage: String
    let unsavedHint: String
    let closeAlertTitle: String
    let closeAlertMessage: String
    let closeAnyway: String
    let quitAlertTitle: String
    let quitAlertMessage: String
    let quitAnyway: String

    // 管理器 — 基本信息
    let basicsTitle: String
    let nameLabel: String
    let namePlaceholder: String
    let nameHelp: String
    let iconLabel: String
    let iconHelp: String
    let typeLabel: String
    let typeToggle: String
    let typeDaemon: String
    let typeHelp: String
    let toggleFootnote: String
    let daemonFootnote: String

    // 管理器 — 参数
    let paramsTitle: String
    let paramsEmpty: String
    let addParam: String
    let deleteParamHelp: String
    let keyLabel: String
    let keyHelp: String
    let displayNameLabel: String
    let displayNamePlaceholder: String
    let displayNameHelp: String
    let controlTypeLabel: String
    let controlTypeHelp: String
    let ptSelect: String
    let ptNumber: String
    let ptText: String
    let ptKey: String
    let keyParamHelp: String
    let chooseKey: String
    let tabCapture: String
    let tabCommonKeys: String
    let tabMouse: String
    let captureIdle: String
    let captureActive: String
    let mouseLeft: String
    let mouseMiddle: String
    let mouseRight: String
    let mouseNote: String
    let bareKeyWarning: String
    let axTitle: String
    let axDetail: String
    let axGrant: String
    let optionsLabel: String
    let optionsHelp: String
    let defaultLabel: String
    let defaultHelp: String
    let presetsLabel: String
    let presetsHelp: String
    let minLabel: String
    let maxLabel: String
    let minMaxHelp: String
    let hintLabel: String
    let hintHelp: String

    // 管理器 — 菜单栏行为
    let menubarTitle: String
    let modeNone: String
    let modeAdd: String
    let modeReplace: String
    let modeHelp: String
    let menubarIconLabel: String
    let countdownToggle: String
    let countdownHelp: String
    let countdownOK: String
    let countdownMissing: String

    // 管理器 — 脚本文件
    let scriptFileHelp: String
    let envVarsLabel: String
    let envVarsHelp: String
    let autoGenerated: String

    // 管理器 — 底栏
    let createButton: String
    let saveButton: String
    let savedToastFormat: String  // %@ = 文件名
    let saveFailedFormat: String  // %@ = 错误信息

    // 图标选择器
    let tabEmoji: String
    let tabSymbols: String
    let tabCustom: String
    let customPlaceholder: String
    let previewLabel: String
    let useButton: String
    let sfNote: String
}

// MARK: - English

extension S {
    static let en = S(
        cancel: "Cancel",
        langSystem: "System Default",

        panelEmpty: "No switches found.\nCreate one via “Manage Scripts” below.",
        manageScripts: "Manage Scripts",
        manageScriptsHelp: "Create, edit, and delete switch scripts",
        reloadHelp: "Rescan the scripts directory",
        quit: "Quit",
        editScriptFile: "Edit Script File",
        revealInFinder: "Reveal in Finder",
        daemonRowHelp: "daemon — long-running process held by the app",
        toggleRowHelp: "toggle — imperative on/off/status commands",
        paramLiveNote: "Switch is on — changes apply immediately",
        languageHelp: "Language",

        turnOffFormat: "Turn Off “%@”",

        managerWindowTitle: "Script Manager — OpenToggle",
        newSwitch: "New Switch",
        openFolderHelp: "Open the scripts directory in Finder",
        deleteToTrash: "Delete (Move to Trash)",
        selectPromptTitle: "Select a switch, or create one",
        selectPromptDetail: "Use ＋ in the lower-left corner",
        showInMenuBar: "Show in menu bar",
        hideFromMenuBar: "Hide from menu bar (kept here, deactivated)",

        discardTitle: "You have unsaved changes",
        discardConfirm: "Discard Changes",
        keepEditing: "Keep Editing",
        discardMessage: "Your changes will be lost if you leave.",
        unsavedHint: "Unsaved changes",
        closeAlertTitle: "Unsaved changes",
        closeAlertMessage: "Closing this window will discard your changes.",
        closeAnyway: "Close Anyway",
        quitAlertTitle: "The script manager has unsaved changes",
        quitAlertMessage: "Quitting now will discard them.",
        quitAnyway: "Quit Anyway",

        basicsTitle: "Basics",
        nameLabel: "Name",
        namePlaceholder: "e.g. Keep Awake",
        nameHelp: """
        Display name shown in the menu bar panel and the manager list.

        On first save, the name derives the script's file name (kebab-cased, \
        numbered on collision). The file name stays stable afterwards — renaming \
        the switch does not rename the file.
        """,
        iconLabel: "Icon",
        iconHelp: """
        Identifies the switch in the panel and list. Two storage forms:

        - any emoji, e.g. `☕️`
        - an SF Symbols name with the `sf:` prefix, e.g. `sf:cup.and.saucer.fill`

        Pick from the grids, or enter a symbol name under **Custom**.
        """,
        typeLabel: "Type",
        typeToggle: "Command toggle",
        typeDaemon: "Daemon process",
        typeHelp: """
        Defines the invocation protocol between the app and the script:

        **toggle (imperative)**
        - On: runs `<script> on`
        - Off: runs `<script> off`
        - State: polls `<script> status` every 5 s; it must print `on` or `off` \
        to stdout. A non-zero exit code marks the state *unknown*.
        - Best for idempotent operations such as changing a system setting.

        **daemon (long-running)**
        - On: runs `<script> run` and holds the process handle
        - Off: sends SIGTERM to the process
        - State: derived from process liveness. Exit 0 is treated as natural \
        completion and resets the switch; a non-zero exit marks it *error*.
        - Best for foreground processes: caffeinate, polling loops, watchers.
        """,
        toggleFootnote: "Runs on/off once each; state is determined by polling the status command.",
        daemonFootnote: "The app spawns and holds the run process; SIGTERM stops it; exit 0 resets the switch.",

        paramsTitle: "Parameters",
        paramsEmpty: "No parameters. Parameters appear as controls in the switch's expandable panel section, and their values are injected into the script as environment variables.",
        addParam: "Add Parameter",
        deleteParamHelp: "Remove this parameter",
        keyLabel: "key",
        keyHelp: """
        Parameter identifier; use `[a-z0-9_]`.

        Injection rule: uppercased, non-alphanumeric characters replaced with `_`, \
        prefixed with `SWITCH_`. Example: `mode` → `$SWITCH_MODE`.
        """,
        displayNameLabel: "Display name",
        displayNamePlaceholder: "e.g. Mode",
        displayNameHelp: "Label shown in the panel. Display-only; not part of the injection.",
        controlTypeLabel: "Control",
        controlTypeHelp: """
        How the parameter is presented in the panel:

        - **Dropdown** — fixed set of options
        - **Number** — numeric field with stepper, bounded by min/max
        - **Text field** — free-form text
        - **Key** — key/mouse picker (capture, common keys, or mouse buttons); \
        the value is a key spec such as `f15` or `cmd+shift+k`, and the script \
        sends it via `"$OPENTOGGLE_BIN" press "$SWITCH_<KEY>"`

        All values are injected as strings.
        """,
        ptSelect: "Dropdown",
        ptNumber: "Number",
        ptText: "Text field",
        ptKey: "Key",
        keyParamHelp: """
        Key spec format: `[modifier+]*key` — e.g. `f15`, `cmd+shift+k`, \
        `mouse:middle`. Modifiers: cmd / shift / opt / ctrl / fn.

        Scripts send the key with `"$OPENTOGGLE_BIN" press "$SWITCH_<KEY>"` \
        (requires a one-time Accessibility permission grant).
        """,
        chooseKey: "Choose Key…",
        tabCapture: "Capture",
        tabCommonKeys: "Common",
        tabMouse: "Mouse",
        captureIdle: "Click, then press the desired key or combination",
        captureActive: "Press a key… (click again to cancel)",
        mouseLeft: "Left Click",
        mouseMiddle: "Middle Click",
        mouseRight: "Right Click",
        mouseNote: "Clicks are sent at the current cursor position.",
        bareKeyWarning: "A bare character key may interfere with normal typing",
        axTitle: "Accessibility permission required",
        axDetail: "Switches that send keystrokes need it — without it macOS silently drops the events and the switch does nothing. After rebuilding, remove the stale OpenToggle entry and add it again.",
        axGrant: "Open Accessibility Settings",
        optionsLabel: "Options",
        optionsHelp: """
        Option set, formatted `label=value`, separated by `|`. Example:

        `Display only=d|Display & system=dis`

        The label is shown in the dropdown; the value is what gets injected. \
        Quote the whole attribute if it contains spaces.
        """,
        defaultLabel: "Default",
        defaultHelp: "Initial value before the user changes it. For dropdowns, use one of the option *values*; empty falls back to the first option.",
        presetsLabel: "Preset buttons",
        presetsHelp: """
        Quick-pick shortcuts for common values, same format as options \
        (`label=value|…`). Rendered as a row of small buttons: clicking one \
        writes its value into the parameter. They coexist with the input field, \
        and the button matching the current value is highlighted.
        """,
        minLabel: "Min",
        maxLabel: "Max",
        minMaxHelp: "Inclusive bounds enforced by both the field and the stepper.",
        hintLabel: "Hint",
        hintHelp: "Auxiliary text: used as the placeholder for text fields, and as a hover tooltip for other control types.",

        menubarTitle: "Menu bar presence while on",
        modeNone: "None",
        modeAdd: "Extra icon",
        modeReplace: "Replace app icon",
        modeHelp: """
        Menu bar behavior while the switch is on (reverts automatically when off):

        - **Extra icon** — creates a dedicated status item; clicking it opens a \
        menu with a direct “turn off” action.
        - **Replace app icon** — temporarily swaps OpenToggle's own icon for \
        this switch's icon.
        """,
        menubarIconLabel: "Menu bar icon",
        countdownToggle: "Show countdown next to the icon",
        countdownHelp: """
        Displays remaining time next to the icon, refreshed every second.

        Requires a **number** parameter with key `duration`, in minutes; \
        `0` means unlimited (no countdown shown).
        """,
        countdownOK: "Countdown reads the “duration” parameter (minutes; 0 = unlimited, hidden)",
        countdownMissing: "No number parameter with key “duration” yet — add one above, or the countdown will not appear",

        scriptFileHelp: """
        The saved script file consists of two sections:

        **Contract header (auto-generated, read-only)** — `# <switch.*>` \
        directive comments generated from the form; the app parses metadata from \
        them. Edit via the form: manual edits are overwritten on save.

        **Script body (editable)** — invocation protocol:
        - toggle: receives `on` | `off` | `status` as `$1`; `status` must print \
        `on`/`off` to stdout
        - daemon: invoked with `run`; use `exec` to start the foreground process \
        so SIGTERM reaches it directly

        Parameter values arrive as environment variables (see the `$SWITCH_*` \
        list). Files are `chmod 755` on save; scripts without the executable bit \
        fall back to `/bin/sh`. A running switch is restarted with the new \
        content after saving.
        """,
        envVarsLabel: "Injected variables",
        envVarsHelp: "The parameters defined above are injected into the script process as these environment variables.",
        autoGenerated: "auto-generated",

        createButton: "Create Switch",
        saveButton: "Save Changes",
        savedToastFormat: "Saved %@",
        saveFailedFormat: "Save failed: %@",

        tabEmoji: "Emoji",
        tabSymbols: "Symbols",
        tabCustom: "Custom",
        customPlaceholder: "Emoji or SF Symbol name (e.g. cup.and.saucer)",
        previewLabel: "Preview:",
        useButton: "Use",
        sfNote: "Browse symbol names in Apple's “SF Symbols” app"
    )
}

// MARK: - 简体中文

extension S {
    static let zh = S(
        cancel: "取消",
        langSystem: "跟随系统",

        panelEmpty: "没有找到开关脚本\n点下方「管理脚本」新建一个",
        manageScripts: "管理脚本",
        manageScriptsHelp: "新建、修改、删除开关脚本",
        reloadHelp: "重新扫描脚本目录",
        quit: "退出",
        editScriptFile: "编辑脚本文件",
        revealInFinder: "在 Finder 中显示",
        daemonRowHelp: "daemon — 由 app 持有的常驻进程",
        toggleRowHelp: "toggle — on/off/status 命令式开关",
        paramLiveNote: "开关开启中，修改立即生效",
        languageHelp: "语言",

        turnOffFormat: "关闭「%@」",

        managerWindowTitle: "脚本管理 — OpenToggle",
        newSwitch: "新建开关",
        openFolderHelp: "在 Finder 中打开脚本目录",
        deleteToTrash: "删除（移到废纸篓）",
        selectPromptTitle: "选择一个开关，或新建",
        selectPromptDetail: "使用左下角的 ＋ 新建",
        showInMenuBar: "在菜单栏显示",
        hideFromMenuBar: "从菜单栏隐藏（保留在此处，暂时停用）",

        discardTitle: "当前开关有未保存的修改",
        discardConfirm: "放弃修改",
        keepEditing: "继续编辑",
        discardMessage: "离开后这些修改将丢失。",
        unsavedHint: "有未保存的修改",
        closeAlertTitle: "有未保存的修改",
        closeAlertMessage: "关闭窗口将丢失这些修改。",
        closeAnyway: "仍要关闭",
        quitAlertTitle: "脚本管理器中有未保存的修改",
        quitAlertMessage: "现在退出将丢失这些修改。",
        quitAnyway: "仍要退出",

        basicsTitle: "基本信息",
        nameLabel: "名称",
        namePlaceholder: "如：Keep Awake",
        nameHelp: """
        开关的显示名称，用于菜单栏面板与管理器列表。

        首次保存时由名称派生脚本文件名（转为 kebab-case，冲突时追加序号）；\
        此后文件名保持稳定，重命名开关不会改变文件名。
        """,
        iconLabel: "图标",
        iconHelp: """
        开关在面板与列表中的标识，支持两种存储形式：

        - 任意 Emoji，如 `☕️`
        - 以 `sf:` 前缀存储的 SF Symbols 名称，如 `sf:cup.and.saucer.fill`

        可从网格中点选，或在「自定义」页输入符号名。
        """,
        typeLabel: "类型",
        typeToggle: "命令式 toggle",
        typeDaemon: "常驻进程 daemon",
        typeHelp: """
        定义 app 与脚本之间的调用协议：

        **toggle（命令式）**
        - 开启：执行 `<script> on`
        - 关闭：执行 `<script> off`
        - 状态：每 5 秒执行 `<script> status`，需向 stdout 输出 `on` 或 `off`；\
        退出码非 0 时状态记为 unknown
        - 适用：修改系统设置等幂等操作

        **daemon（常驻进程）**
        - 开启：执行 `<script> run` 并持有进程句柄
        - 关闭：向进程发送 SIGTERM
        - 状态：以进程存活为准；exit 0 视为自然结束并自动复位开关，\
        非零退出码标记为 error
        - 适用：caffeinate、轮询循环等前台长驻任务
        """,
        toggleFootnote: "on/off 各执行一次；状态由 status 命令轮询判定。",
        daemonFootnote: "app 启动并持有 run 进程；SIGTERM 终止；exit 0 自动复位。",

        paramsTitle: "参数",
        paramsEmpty: "暂无参数。参数会出现在面板中该开关的展开区，值以环境变量注入脚本进程。",
        addParam: "添加参数",
        deleteParamHelp: "删除该参数",
        keyLabel: "key",
        keyHelp: """
        参数标识符，建议使用 `[a-z0-9_]`。

        注入规则：转大写、非字母数字字符替换为 `_`、添加前缀 `SWITCH_`。\
        例：`mode` → `$SWITCH_MODE`。
        """,
        displayNameLabel: "显示名",
        displayNamePlaceholder: "如：模式",
        displayNameHelp: "面板参数区显示的标签，仅用于展示，不参与注入。",
        controlTypeLabel: "控件类型",
        controlTypeHelp: """
        参数在面板中的呈现形式：

        - **下拉选择** — 固定候选集
        - **数字** — 带边界约束的数字输入 + 步进器
        - **填写框** — 自由文本
        - **按键** — 按键/鼠标选择器（捕获、常用键、鼠标键）；值为按键规范如 \
        `f15`、`cmd+shift+k`，脚本用 `"$OPENTOGGLE_BIN" press "$SWITCH_<KEY>"` 发送

        所有值均以字符串形式注入。
        """,
        ptSelect: "下拉选择",
        ptNumber: "数字",
        ptText: "填写框",
        ptKey: "按键",
        keyParamHelp: """
        按键规范格式：`[修饰键+]*键名` — 如 `f15`、`cmd+shift+k`、\
        `mouse:middle`。修饰键：cmd / shift / opt / ctrl / fn。

        脚本用 `"$OPENTOGGLE_BIN" press "$SWITCH_<KEY>"` 发送按键\
        （需要一次性授予「辅助功能」权限）。
        """,
        chooseKey: "选择按键…",
        tabCapture: "捕获",
        tabCommonKeys: "常用键",
        tabMouse: "鼠标",
        captureIdle: "点击此处，然后按下想要的键或组合键",
        captureActive: "请按下按键…（再次点击取消）",
        mouseLeft: "鼠标左键",
        mouseMiddle: "鼠标中键",
        mouseRight: "鼠标右键",
        mouseNote: "点击发送在当前光标位置。",
        bareKeyWarning: "无修饰键的字符键可能干扰正常输入",
        axTitle: "需要辅助功能权限",
        axDetail: "发送按键的开关依赖此权限——未授权时 macOS 会静默丢弃事件，开关看似开启却毫无作用。重新构建后请先移除列表中失效的 OpenToggle 条目再重新添加。",
        axGrant: "打开辅助功能设置",
        optionsLabel: "选项",
        optionsHelp: """
        候选集定义，格式 `label=value`，多项以 `|` 分隔。例：

        `仅屏幕=d|屏幕与任务=dis`

        label 用于显示，value 为实际注入值。属性含空格时整体以双引号包裹。
        """,
        defaultLabel: "默认值",
        defaultHelp: "参数的初始值。下拉选择类型应填候选项的 value；留空时取第一个候选项。",
        presetsLabel: "快捷按钮",
        presetsHelp: """
        常用值的快捷入口，格式与选项相同（`label=value|…`）。

        在面板中渲染为一组小按钮：点击即写入该值；与输入框并存，\
        当前值匹配的按钮高亮。适合时长、常用地址等场景。
        """,
        minLabel: "最小值",
        maxLabel: "最大值",
        minMaxHelp: "数字输入与步进器共同遵守的取值边界（含端点）。",
        hintLabel: "提示",
        hintHelp: "辅助说明文字：填写框类型作为占位符显示，其余类型作为悬停提示（tooltip）。",

        menubarTitle: "开启时的菜单栏行为",
        modeNone: "不显示",
        modeAdd: "新增图标",
        modeReplace: "替换主图标",
        modeHelp: """
        开关处于开启状态期间的菜单栏行为（关闭后自动恢复）：

        - **新增图标** — 创建独立的状态栏项；点击弹出菜单，可直接关闭该开关
        - **替换主图标** — 将 OpenToggle 主图标临时替换为该开关的图标
        """,
        menubarIconLabel: "菜单栏图标",
        countdownToggle: "在图标旁显示倒计时",
        countdownHelp: """
        在菜单栏图标旁显示剩余时间，每秒刷新。

        依赖约定参数：key 为 `duration` 的**数字**参数，单位为分钟；\
        `0` 表示不限时（不显示倒计时）。
        """,
        countdownOK: "倒计时读取「duration」参数（分钟；0 = 不限时，不显示）",
        countdownMissing: "尚无 key 为 duration 的数字参数——请在上方添加，否则倒计时不会显示",

        scriptFileHelp: """
        保存的脚本文件由两部分构成：

        **契约头（自动生成，只读）** — 由左侧表单生成的 `# <switch.*>` 指令注释，\
        app 据此解析元数据。请通过表单修改；手工编辑将在下次保存时被覆盖。

        **脚本正文（可编辑）** — 调用协议：
        - toggle：以 `$1` 接收 `on` | `off` | `status`；`status` 需向 stdout \
        输出 `on`/`off`
        - daemon：以 `run` 调用；应使用 `exec` 启动前台进程，确保 SIGTERM 可直达

        参数值通过环境变量传入（见 `$SWITCH_*` 列表）。保存时自动 `chmod 755`；\
        无执行位的脚本回退以 `/bin/sh` 解释执行。正在运行的开关在保存后会以新内容重启。
        """,
        envVarsLabel: "注入变量",
        envVarsHelp: "上方定义的参数将以这些环境变量注入脚本进程。",
        autoGenerated: "自动生成",

        createButton: "创建开关",
        saveButton: "保存修改",
        savedToastFormat: "已保存 %@",
        saveFailedFormat: "保存失败：%@",

        tabEmoji: "Emoji",
        tabSymbols: "图标",
        tabCustom: "自定义",
        customPlaceholder: "Emoji 或 SF Symbol 名（如 cup.and.saucer）",
        previewLabel: "预览：",
        useButton: "使用",
        sfNote: "符号名可在 Apple「SF Symbols」app 中查询"
    )
}
